// Database types (generated by Prisma)
import type { User, Board, BoardMember, Column, Task, Comment, Activity, Notification, MemberRole } from '@prisma/client'
export type { User, Board, BoardMember, Column, Task, Comment, Activity, Notification }

// Enums
export type { MemberRole, Priority, ActivityType, NotificationType } from '@prisma/client'

// Extended types with relations
export interface BoardWithRelations extends Board {
  columns: Column[]
  members: BoardMemberWithUser[]
  activities: Activity[]
}

export interface BoardMemberWithUser extends Omit<BoardMember, 'user'> {
  user: User
  role: MemberRole
}

export interface TaskWithRelations extends Task {
  column: Column
  assignee?: User
  comments: CommentWithUser[]
}

export interface CommentWithUser extends Comment {
  user: User
}

export interface ActivityWithRelations extends Activity {
  user: User
  task?: Task
  board: Board
}

// export interface BoardTemplateWithUser extends BoardTemplate {
//   createdBy: User
// } // Temporarily disabled

export interface NotificationWithUser extends Notification {
  user: User
}

// API Response types
export interface ApiResponse<T = unknown> {
  success: boolean
  data?: T
  error?: string
  message?: string
}

export interface PaginatedResponse<T> extends ApiResponse<T[]> {
  pagination: {
    page: number
    limit: number
    total: number
    totalPages: number
  }
}

// WebSocket types
export interface WebSocketEvent {
  type: string
  data: unknown
  timestamp: number
}

export interface UserPresenceEvent extends WebSocketEvent {
  type: 'user:joined' | 'user:left'
  data: {
    userId: string
    user?: User
  }
}

export interface BoardEvent extends WebSocketEvent {
  type: 'board:updated'
  data: Board
}

export interface ColumnEvent extends WebSocketEvent {
  type: 'column:created' | 'column:updated' | 'column:deleted'
  data: Column | { id: string }
}

export interface TaskEvent extends WebSocketEvent {
  type: 'task:created' | 'task:updated' | 'task:deleted' | 'task:moved'
  data: Task | { id: string } | { id: string; columnId: string; position: number }
}

export interface MemberEvent extends WebSocketEvent {
  type: 'member:added' | 'member:removed' | 'member:updated'
  data: BoardMemberWithUser | { userId: string }
}

export interface NotificationEvent extends WebSocketEvent {
  type: 'notification:created'
  data: NotificationWithUser
}

// Cache types
export interface CacheEntry<T> {
  data: T
  timestamp: number
  ttl: number
}

// Error types
export class ValidationError extends Error {
  constructor(message: string, public field?: string) {
    super(message)
    this.name = 'ValidationError'
  }
}

export class NotFoundError extends Error {
  constructor(resource: string) {
    super(`${resource} not found`)
    this.name = 'NotFoundError'
  }
}

export class ForbiddenError extends Error {
  constructor(message = 'Access denied') {
    super(message)
    this.name = 'ForbiddenError'
  }
}

// Utility types
export type Optional<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>

export type RequireAtLeastOne<T, Keys extends keyof T = keyof T> = Pick<T, Exclude<keyof T, Keys>> & {
  [K in Keys]-?: Required<Pick<T, K>> & Partial<Pick<T, Keys>>
}[Keys]

// Form types
export interface LoginForm {
  email: string
  password: string
}

export interface RegisterForm {
  name: string
  email: string
  password: string
  confirmPassword: string
}

// Search and filtering types
export interface SearchFilters {
  type?: 'boards' | 'tasks' | 'users'
  assigneeId?: string
  priority?: import('@prisma/client').Priority
  dueDateFrom?: Date
  dueDateTo?: Date
  labels?: string[]
  boardId?: string
}

export interface SearchResult {
  type: 'board' | 'task' | 'user'
  id: string
  title: string
  description?: string
  boardId?: string
  assignee?: Pick<User, 'id' | 'name' | 'email' | 'avatar'>
  priority?: import('@prisma/client').Priority
  dueDate?: Date
  labels?: string[]
  matchScore: number
  highlightedText?: string
}

export interface MentionData {
  userId: string
  userName: string
  avatar?: string
}

// Component prop types
export interface ComponentWithChildren {
  children: React.ReactNode
}

export interface ComponentWithClassName {
  className?: string
}
